/**
 * Reads the StyleTarot TSV and writes src/data/styletarot/cards.ts
 * Usage: npm run db:gen-tarot-cards
 */

import fs from "fs";
import path from "path";

const TSV_PATH = path.join(process.cwd(), ".planning", "StyleTerot Cards - Sheet1.tsv");
const OUT_DIR = path.join(process.cwd(), "src", "data", "styletarot");
const OUT_PATH = path.join(OUT_DIR, "cards.ts");

// Fix known filename typos in the TSV
const FILENAME_FIXES: Record<string, string> = {
  "Stippling,jpg": "Stippling.jpg",
  "Installation Art.jpg": "Installation_Art.jpg",
};

// Strip accents from a filename so TSV entries like "Paul_Cézanne.jpg"
// resolve to the unaccented file actually stored on disk ("Paul_Cezanne.jpg").
// NFD decomposition splits combined chars into base + combining mark;
// the regex then removes the combining marks.
function normalizeFilename(filename: string): string {
  return filename.normalize("NFD").replace(/[̀-ͯ]/g, "");
}

// Add missing descriptions
const DESCRIPTION_OVERRIDES: Record<string, string> = {
  Difference:
    "Art illustrating the contrast or difference between two things — subjects, styles, media, settings, or concepts — revealing meaning through juxtaposition and comparison.",
};

const CARD_TYPES = [
  "movement",
  "subject",
  "media",
  "artist",
  "inspiration",
  "technique",
  "setting",
  "situation",
  "pop culture",
  "location",
] as const;

type CardType = (typeof CARD_TYPES)[number];

interface TarotCard {
  index: number;
  creator: string;
  title: string;
  description: string;
  type: CardType;
  imageFilename: string;
}

function main() {
  const raw = fs.readFileSync(TSV_PATH, "utf-8");
  const lines = raw.split("\n").filter((l) => l.trim());

  // Skip header row (line 0 is "index\tcreator\t...")
  const dataLines = lines.slice(1);

  const cards: TarotCard[] = [];

  for (const line of dataLines) {
    const parts = line.split("\t");
    if (parts.length < 6) continue;

    const indexStr = parts[0].trim();
    const index = parseInt(indexStr, 10);
    if (isNaN(index)) continue;

    const creator = parts[1].trim();
    const title = parts[2].trim();
    let description = parts[3].trim();
    const typeRaw = parts[4].trim().toLowerCase() as CardType;
    // Last column is imageFilename, second-to-last is image (display name)
    // TSV has 7 columns: index, creator, title, description, type, image, imageFilename
    const imageFilename = (parts[6] ?? parts[5] ?? "").trim();

    // Apply description overrides
    if (DESCRIPTION_OVERRIDES[title]) {
      description = DESCRIPTION_OVERRIDES[title];
    }

    // Normalize accents first, then apply any remaining manual fixes
    const normalizedFilename = normalizeFilename(imageFilename);
    const fixedFilename = FILENAME_FIXES[normalizedFilename] ?? normalizedFilename;

    cards.push({
      index,
      creator,
      title,
      description,
      type: typeRaw,
      imageFilename: fixedFilename,
    });
  }

  console.log(`Parsed ${cards.length} cards`);

  // Build TypeScript output
  const lines_out: string[] = [
    `// AUTO-GENERATED by scripts/generate-tarot-cards.ts`,
    `// Do not edit manually — re-run the script to regenerate.`,
    ``,
    `export type CardType =`,
    `  | "movement"`,
    `  | "subject"`,
    `  | "media"`,
    `  | "artist"`,
    `  | "inspiration"`,
    `  | "technique"`,
    `  | "setting"`,
    `  | "situation"`,
    `  | "pop culture"`,
    `  | "location";`,
    ``,
    `export interface TarotCard {`,
    `  index: number;`,
    `  creator: string;`,
    `  title: string;`,
    `  description: string;`,
    `  type: CardType;`,
    `  imageFilename: string;`,
    `}`,
    ``,
    `export const TAROT_CARDS: TarotCard[] = [`,
  ];

  for (const card of cards) {
    lines_out.push(`  {`);
    lines_out.push(`    index: ${card.index},`);
    lines_out.push(`    creator: ${JSON.stringify(card.creator)},`);
    lines_out.push(`    title: ${JSON.stringify(card.title)},`);
    lines_out.push(`    description: ${JSON.stringify(card.description)},`);
    lines_out.push(`    type: ${JSON.stringify(card.type)},`);
    lines_out.push(`    imageFilename: ${JSON.stringify(card.imageFilename)},`);
    lines_out.push(`  },`);
  }

  lines_out.push(`];`);
  lines_out.push(``);
  lines_out.push(`export const CARD_TYPE_COLORS: Record<CardType, string> = {`);
  lines_out.push(`  movement: "oklch(0.42 0.22 285)",`);
  lines_out.push(`  artist: "oklch(0.60 0.14 195)",`);
  lines_out.push(`  media: "oklch(0.78 0.15 85)",`);
  lines_out.push(`  technique: "oklch(0.65 0.17 30)",`);
  lines_out.push(`  subject: "oklch(0.55 0.18 145)",`);
  lines_out.push(`  setting: "oklch(0.50 0.18 220)",`);
  lines_out.push(`  inspiration: "oklch(0.65 0.14 355)",`);
  lines_out.push(`  situation: "oklch(0.65 0.14 355)",`);
  lines_out.push(`  "pop culture": "oklch(0.55 0.20 25)",`);
  lines_out.push(`  location: "oklch(0.60 0.16 175)",`);
  lines_out.push(`};`);
  lines_out.push(``);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_PATH, lines_out.join("\n"), "utf-8");
  console.log(`Written to ${OUT_PATH}`);
}

main();
