#!/usr/bin/env python3
"""Add stylebearMovements and stylebearMedia translation namespaces to all locale files.

Every locale gets EVERY key. Untranslated items fall back to the English name so
no runtime fallback logic is needed in client components.
"""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "messages")

# All art movement names (English — used as keys in every locale)
MOVEMENTS_EN = [
    "2D Cartoon","3D Cartoon","ASCII Art","Abstract Expressionism","Abstract Illusionism",
    "Abstract","Academic Art","Action Painting","Aestheticism","Afrofuturism","Altermodern",
    "American Barbizon School","American Impressionism","American Realism","American Romanticism",
    "American Scene Painting","Analytical Art","Antipodeans","Arabesque","Arbeitsrat für Kunst",
    "Art & Language","Art Brut","Art Deco","Art Informel","Art Nouveau","Arte Povera",
    "Artistic Photography","Arts and Crafts Movement","Ashcan School","Assemblage",
    "Australian Tonalism","Auto-Destructive Art","Barbizon School","Baroque","Bauhaus",
    "Bengal School","Berlin Secession","Biomechanical","Black Arts Movement","Boho",
    "Brutalism","Celtic Revival","Classical Realism","Cloisonnism","CoBrA Art Movement",
    "Color Field","Computer Art","Conceptual Art","Concrete Art","Constructivism",
    "Context Art","Crystal Cubism","Cubism","Cubo-Futurism","Cyberpunk","Cynical Realism",
    "Dada","Danube School","Dau-al-Set","De Stijl","Deconstructivism","Digital Art",
    "Disco style","Ecological Art","Environmental Art","Excessivism","Expressionism",
    "Fantastic Realism","Fantasy Art","Fauvism","Feminist Art","Figuration Libre",
    "Figurative Art","Figurativism","Fine Art","Fluxus","Folk Art","Funk Art","Furry Art",
    "Futurism","Generative Art","Geometric Abstract Art","German Romanticism","Glam Rock",
    "Gothic","Graffiti","Grunge","Gutai Group","Hair Metal","Happening","Harlem Renaissance",
    "Heavy Metal","Heidelberg School","Hip-Hop","Hippie","Holography","Hudson River School",
    "Hurufiyya","Hypermodernism","Hyperrealism","Impressionism","Incoherents",
    "Institutional Critique","Interactive Art","International Gothic","International Typographic",
    "Jazz","Josei Anime","Khokhloma","Kinetic Art","Kinetic Pointillism","Kitsch","Land Art",
    "Les Automatistes","Les Nabis","Letterism","Light and Space","Lowbrow",
    "Lyrical Abstraction","Magic Realism","Mail Art","Mannerism","Maximalism","Mecha Anime",
    "Mid-Century Modern","Minimalism","Modernism","Modular Constructivism","Naive Art",
    "Naturalism","Neo-Dada","Neo-Expressionism","Neo-Fauvism","Neo-Figurative","Neo-Geo",
    "Neo-Primitivism","Neo-Romanticism","Neoclassicism","Neoism","Neoplasticism",
    "New Objectivity","New Sculpture","Nordic Surrealism","Northwest School","Nuclear Art",
    "Objective Abstraction","Op Art","Optical Illusion","Orphism","Panfuturism","Paris School",
    "Photorealism","Pin-Up","Pixel Art","Plasticien","Plein Air","Pointillism","Pop Art",
    "Pop Surrealism","Post-Impressionism","Postminimalism","Pre-Raphaelite","Precisionism",
    "Primitivism","Private Press","Process Art","Psychedelic","Punk","Purism","Qajar",
    "Quito School","Rasquache","Rayonism","Realism","Reggae","Regionalism","Remodernism",
    "Renaissance (Early)","Renaissance (High)","Renaissance (Northern)","Renaissance (generic)",
    "Retrofuturism","Rococo","Romanesque","Romanticism","Samikshavad","Seinen Anime",
    "Serial Art","Shin Hanga","Shock Art","Shojo Anime","Shonen Anime","Ska",
    "Socialist Realism","Sots","Space Art","Steampunk","Still Life Hyperrealism","Stuckism",
    "Sumatraism","Superflat","Suprematism","Surreal Photography","Surrealism","Symbolism",
    "Synchromism","Synthetism","Sōsaku Hanga","Tachisme","Temporary Art","Tonalism",
    "Toyism","Transgressive","Ukiyo-e","Underground Comix","Vancouver School","Vanitas",
    "Vaporwave","Verism","Video Art","Viennese Actionism","Vorticism",
]

# All media type names (English — used as keys in every locale)
MEDIA_EN = [
    "Acrylic Impasto","Acrylic Painting","Acrylic Pour","Alcohol Ink","Algorithmic Art",
    "Batik Fabric","Book Art","Béton (cement)","CGI","Ceramics","Charcoal","Clay Sculpture",
    "Clayboard Etching","Collage","Crayons","Digital Painting","Driftwood","Enamel",
    "Encaustic Art","Etching","Fabric","Fairy Lights","Felting","Food","Found Objects",
    "Fractal","Fresco Painting","Gems/Crystals","Glass","Glitch","Graphite","Hardware",
    "Ice","Ink","Interactive Digital Art","LEDs","Lacquer","Lasers",
    "Leaf and Nature Printing","Leather Carving","Leather","Light Projection",
    "Linocut Printing","Markers","Metal","Neon","Oil Painting","Origami","Paper Quilling",
    "Paper Sculpture","Papier-mâché","Pastel","Pencil","Photography","Plaster Scupture",
    "Polymer Clay","Postage Stamps","Printmaking","Pyrography","Quilt","Raku Pottery",
    "Recycled Materials","Relief Printing","Rubber Stamps","Salt","Sand","Scrimshaw",
    "Sgraffito","Shadow Play","Silk Painting","Stencils","Stone Carving","Tapestry",
    "Terra-cotta","Textile Art","Thread","Watercolor","Wax","Weaving","Whittling",
    "Wire Sculpture","Wood Sculpture","Woodblock Printing","Yarn",
]

# ─── Partial translations per locale ────────────────────────────────────────
# Any key not listed here will use the English name.

MOVEMENTS_PARTIAL = {
    "ja": {
        "2D Cartoon": "2Dアニメ",
        "3D Cartoon": "3Dアニメ",
        "Abstract": "抽象芸術",
        "Abstract Expressionism": "抽象表現主義",
        "Academic Art": "アカデミズム絵画",
        "Action Painting": "アクション・ペインティング",
        "Art Brut": "アール・ブリュット",
        "Art Deco": "アール・デコ",
        "Art Informel": "アンフォルメル",
        "Art Nouveau": "アール・ヌーヴォー",
        "Arts and Crafts Movement": "アーツ・アンド・クラフツ運動",
        "Baroque": "バロック",
        "Bauhaus": "バウハウス",
        "Cloisonnism": "クロワゾニスム",
        "Color Field": "カラーフィールド絵画",
        "Conceptual Art": "コンセプチュアル・アート",
        "Constructivism": "構成主義",
        "Cubism": "キュビスム",
        "Cyberpunk": "サイバーパンク",
        "Dada": "ダダイスム",
        "De Stijl": "デ・ステイル",
        "Digital Art": "デジタルアート",
        "Environmental Art": "環境芸術",
        "Expressionism": "表現主義",
        "Fantasy Art": "ファンタジーアート",
        "Fauvism": "フォーヴィスム",
        "Figurative Art": "具象芸術",
        "Fine Art": "ファインアート",
        "Folk Art": "民俗芸術",
        "Futurism": "未来派",
        "Generative Art": "ジェネラティブアート",
        "Geometric Abstract Art": "幾何学的抽象芸術",
        "Gothic": "ゴシック",
        "Graffiti": "グラフィティ",
        "Harlem Renaissance": "ハーレム・ルネサンス",
        "Hyperrealism": "ハイパーリアリズム",
        "Impressionism": "印象派",
        "Josei Anime": "女性向けアニメ",
        "Kinetic Art": "キネティックアート",
        "Land Art": "ランドアート",
        "Mannerism": "マニエリスム",
        "Mecha Anime": "メカアニメ",
        "Mid-Century Modern": "ミッドセンチュリーモダン",
        "Minimalism": "ミニマリズム",
        "Modernism": "モダニズム",
        "Naive Art": "素朴派",
        "Naturalism": "自然主義",
        "Neoclassicism": "新古典主義",
        "Neo-Expressionism": "新表現主義",
        "Op Art": "オプ・アート",
        "Photorealism": "フォトリアリズム",
        "Pixel Art": "ピクセルアート",
        "Plein Air": "戸外写生",
        "Pointillism": "点描主義",
        "Pop Art": "ポップアート",
        "Pop Surrealism": "ポップ・シュルレアリスム",
        "Post-Impressionism": "後期印象派",
        "Pre-Raphaelite": "ラファエル前派",
        "Psychedelic": "サイケデリック",
        "Realism": "リアリズム",
        "Renaissance (Early)": "初期ルネサンス",
        "Renaissance (High)": "盛期ルネサンス",
        "Renaissance (Northern)": "北方ルネサンス",
        "Renaissance (generic)": "ルネサンス",
        "Rococo": "ロココ",
        "Romanesque": "ロマネスク",
        "Romanticism": "ロマン主義",
        "Seinen Anime": "青年アニメ",
        "Shin Hanga": "新版画",
        "Shojo Anime": "少女アニメ",
        "Shonen Anime": "少年アニメ",
        "Socialist Realism": "社会主義リアリズム",
        "Steampunk": "スチームパンク",
        "Superflat": "スーパーフラット",
        "Suprematism": "シュプレマティスム",
        "Surrealism": "シュルレアリスム",
        "Symbolism": "象徴主義",
        "Ukiyo-e": "浮世絵",
        "Vaporwave": "ヴェーパーウェーブ",
        "Video Art": "ビデオアート",
        "Sōsaku Hanga": "創作版画",
    },
    "zh": {
        "2D Cartoon": "2D卡通",
        "3D Cartoon": "3D卡通",
        "Abstract": "抽象艺术",
        "Abstract Expressionism": "抽象表现主义",
        "Academic Art": "学院派艺术",
        "Action Painting": "行动绘画",
        "Art Brut": "原生艺术",
        "Art Deco": "装饰艺术",
        "Art Nouveau": "新艺术运动",
        "Baroque": "巴洛克",
        "Bauhaus": "包豪斯",
        "Color Field": "色域绘画",
        "Conceptual Art": "概念艺术",
        "Constructivism": "构成主义",
        "Cubism": "立体主义",
        "Cyberpunk": "赛博朋克",
        "Dada": "达达主义",
        "De Stijl": "风格派",
        "Digital Art": "数字艺术",
        "Expressionism": "表现主义",
        "Fantasy Art": "幻想艺术",
        "Fauvism": "野兽派",
        "Folk Art": "民间艺术",
        "Futurism": "未来主义",
        "Generative Art": "生成艺术",
        "Geometric Abstract Art": "几何抽象艺术",
        "Gothic": "哥特式",
        "Graffiti": "涂鸦",
        "Harlem Renaissance": "哈莱姆文艺复兴",
        "Hyperrealism": "超写实主义",
        "Impressionism": "印象主义",
        "Kinetic Art": "动态艺术",
        "Land Art": "大地艺术",
        "Mannerism": "矫饰主义",
        "Minimalism": "极简主义",
        "Modernism": "现代主义",
        "Naive Art": "素人艺术",
        "Naturalism": "自然主义",
        "Neoclassicism": "新古典主义",
        "Neo-Expressionism": "新表现主义",
        "Op Art": "欧普艺术",
        "Photorealism": "照相写实主义",
        "Pixel Art": "像素艺术",
        "Pointillism": "点彩派",
        "Pop Art": "波普艺术",
        "Post-Impressionism": "后印象主义",
        "Pre-Raphaelite": "拉斐尔前派",
        "Psychedelic": "迷幻艺术",
        "Realism": "现实主义",
        "Renaissance (Early)": "早期文艺复兴",
        "Renaissance (High)": "盛期文艺复兴",
        "Renaissance (Northern)": "北方文艺复兴",
        "Renaissance (generic)": "文艺复兴",
        "Rococo": "洛可可",
        "Romanesque": "罗马式",
        "Romanticism": "浪漫主义",
        "Socialist Realism": "社会主义现实主义",
        "Steampunk": "蒸汽朋克",
        "Superflat": "超扁平",
        "Suprematism": "至上主义",
        "Surrealism": "超现实主义",
        "Symbolism": "象征主义",
        "Ukiyo-e": "浮世绘",
        "Vaporwave": "蒸汽波",
        "Video Art": "录像艺术",
    },
    "ru": {
        "Abstract": "Абстрактное искусство",
        "Abstract Expressionism": "Абстрактный экспрессионизм",
        "Art Brut": "Ар-брют",
        "Art Deco": "Ар-деко",
        "Art Nouveau": "Ар-нуво",
        "Baroque": "Барокко",
        "Bauhaus": "Баухаус",
        "Conceptual Art": "Концептуальное искусство",
        "Constructivism": "Конструктивизм",
        "Cubism": "Кубизм",
        "Cyberpunk": "Киберпанк",
        "Dada": "Дадаизм",
        "De Stijl": "Де Стейл",
        "Digital Art": "Цифровое искусство",
        "Expressionism": "Экспрессионизм",
        "Fantasy Art": "Фэнтезийное искусство",
        "Fauvism": "Фовизм",
        "Folk Art": "Народное искусство",
        "Futurism": "Футуризм",
        "Gothic": "Готика",
        "Graffiti": "Граффити",
        "Hyperrealism": "Гиперреализм",
        "Impressionism": "Импрессионизм",
        "Kinetic Art": "Кинетическое искусство",
        "Land Art": "Ленд-арт",
        "Mannerism": "Маньеризм",
        "Minimalism": "Минимализм",
        "Modernism": "Модернизм",
        "Naturalism": "Натурализм",
        "Neoclassicism": "Неоклассицизм",
        "Neo-Expressionism": "Неоэкспрессионизм",
        "Op Art": "Оп-арт",
        "Photorealism": "Фотореализм",
        "Pixel Art": "Пиксельное искусство",
        "Pointillism": "Пуантилизм",
        "Pop Art": "Поп-арт",
        "Post-Impressionism": "Постимпрессионизм",
        "Pre-Raphaelite": "Прерафаэлиты",
        "Psychedelic": "Психоделическое искусство",
        "Realism": "Реализм",
        "Renaissance (Early)": "Раннее Возрождение",
        "Renaissance (High)": "Высокое Возрождение",
        "Renaissance (Northern)": "Северное Возрождение",
        "Renaissance (generic)": "Возрождение",
        "Rococo": "Рококо",
        "Romanesque": "Романский стиль",
        "Romanticism": "Романтизм",
        "Socialist Realism": "Социалистический реализм",
        "Steampunk": "Стимпанк",
        "Suprematism": "Супрематизм",
        "Surrealism": "Сюрреализм",
        "Symbolism": "Символизм",
        "Ukiyo-e": "Укиё-э",
        "Video Art": "Видеоарт",
    },
    "fr": {
        "Abstract": "Art abstrait",
        "Abstract Expressionism": "Expressionnisme abstrait",
        "Art Brut": "Art brut",
        "Art Deco": "Art déco",
        "Art Nouveau": "Art nouveau",
        "Baroque": "Baroque",
        "Bauhaus": "Bauhaus",
        "Cloisonnism": "Cloisonnisme",
        "Color Field": "Color field",
        "Conceptual Art": "Art conceptuel",
        "Constructivism": "Constructivisme",
        "Cubism": "Cubisme",
        "Dada": "Dadaïsme",
        "De Stijl": "De Stijl",
        "Expressionism": "Expressionnisme",
        "Fauvism": "Fauvisme",
        "Folk Art": "Art populaire",
        "Futurism": "Futurisme",
        "Gothic": "Gothique",
        "Impressionism": "Impressionnisme",
        "Les Nabis": "Les Nabis",
        "Mannerism": "Maniérisme",
        "Minimalism": "Minimalisme",
        "Modernism": "Modernisme",
        "Naturalism": "Naturalisme",
        "Neoclassicism": "Néoclassicisme",
        "Op Art": "Op art",
        "Photorealism": "Photoréalisme",
        "Pointillism": "Pointillisme",
        "Pop Art": "Pop art",
        "Post-Impressionism": "Post-impressionnisme",
        "Pre-Raphaelite": "Préraphaélisme",
        "Realism": "Réalisme",
        "Renaissance (Early)": "Première Renaissance",
        "Renaissance (High)": "Haute Renaissance",
        "Renaissance (Northern)": "Renaissance du Nord",
        "Renaissance (generic)": "Renaissance",
        "Rococo": "Rococo",
        "Romanticism": "Romantisme",
        "Surrealism": "Surréalisme",
        "Symbolism": "Symbolisme",
    },
    "de": {
        "Abstract": "Abstrakte Kunst",
        "Abstract Expressionism": "Abstrakter Expressionismus",
        "Art Deco": "Art déco",
        "Art Nouveau": "Jugendstil",
        "Baroque": "Barock",
        "Bauhaus": "Bauhaus",
        "Conceptual Art": "Konzeptkunst",
        "Constructivism": "Konstruktivismus",
        "Cubism": "Kubismus",
        "Dada": "Dadaismus",
        "De Stijl": "De Stijl",
        "Expressionism": "Expressionismus",
        "Fauvism": "Fauvismus",
        "Folk Art": "Volkskunst",
        "Futurism": "Futurismus",
        "Gothic": "Gotik",
        "Impressionism": "Impressionismus",
        "Mannerism": "Manierismus",
        "Minimalism": "Minimalismus",
        "Modernism": "Modernismus",
        "Naturalism": "Naturalismus",
        "Neoclassicism": "Neoklassizismus",
        "New Objectivity": "Neue Sachlichkeit",
        "Op Art": "Op-Art",
        "Photorealism": "Fotorealismus",
        "Pointillism": "Pointillismus",
        "Pop Art": "Pop-Art",
        "Post-Impressionism": "Postimpressionismus",
        "Pre-Raphaelite": "Präraffaeliten",
        "Realism": "Realismus",
        "Renaissance (Early)": "Frührenaissance",
        "Renaissance (High)": "Hochrenaissance",
        "Renaissance (Northern)": "Nordische Renaissance",
        "Renaissance (generic)": "Renaissance",
        "Rococo": "Rokoko",
        "Romanticism": "Romantik",
        "Surrealism": "Surrealismus",
        "Symbolism": "Symbolismus",
    },
    "it": {
        "Abstract": "Arte astratta",
        "Abstract Expressionism": "Espressionismo astratto",
        "Art Deco": "Art déco",
        "Art Nouveau": "Liberty",
        "Baroque": "Barocco",
        "Bauhaus": "Bauhaus",
        "Conceptual Art": "Arte concettuale",
        "Constructivism": "Costruttivismo",
        "Cubism": "Cubismo",
        "Dada": "Dadaismo",
        "Expressionism": "Espressionismo",
        "Fauvism": "Fauvismo",
        "Folk Art": "Arte popolare",
        "Futurism": "Futurismo",
        "Gothic": "Gotico",
        "Impressionism": "Impressionismo",
        "Mannerism": "Manierismo",
        "Minimalism": "Minimalismo",
        "Modernism": "Modernismo",
        "Naturalism": "Naturalismo",
        "Neoclassicism": "Neoclassicismo",
        "Op Art": "Op art",
        "Photorealism": "Fotorealismo",
        "Pointillism": "Puntinismo",
        "Pop Art": "Pop art",
        "Post-Impressionism": "Post-impressionismo",
        "Pre-Raphaelite": "Preraffaellismo",
        "Realism": "Realismo",
        "Renaissance (Early)": "Primo Rinascimento",
        "Renaissance (High)": "Alto Rinascimento",
        "Renaissance (Northern)": "Rinascimento nordico",
        "Renaissance (generic)": "Rinascimento",
        "Rococo": "Rococò",
        "Romanticism": "Romanticismo",
        "Surrealism": "Surrealismo",
        "Symbolism": "Simbolismo",
    },
    "pt": {
        "Abstract": "Arte abstrata",
        "Abstract Expressionism": "Expressionismo abstrato",
        "Art Deco": "Arte déco",
        "Art Nouveau": "Arte nova",
        "Baroque": "Barroco",
        "Bauhaus": "Bauhaus",
        "Conceptual Art": "Arte conceitual",
        "Constructivism": "Construtivismo",
        "Cubism": "Cubismo",
        "Dada": "Dadaísmo",
        "Expressionism": "Expressionismo",
        "Fauvism": "Fauvismo",
        "Folk Art": "Arte popular",
        "Futurism": "Futurismo",
        "Gothic": "Gótico",
        "Impressionism": "Impressionismo",
        "Mannerism": "Maneirismo",
        "Minimalism": "Minimalismo",
        "Modernism": "Modernismo",
        "Naturalism": "Naturalismo",
        "Neoclassicism": "Neoclassicismo",
        "Op Art": "Op art",
        "Photorealism": "Fotorrealismo",
        "Pointillism": "Pontilhismo",
        "Pop Art": "Arte pop",
        "Post-Impressionism": "Pós-impressionismo",
        "Pre-Raphaelite": "Pré-Rafaelismo",
        "Realism": "Realismo",
        "Renaissance (Early)": "Primeiro Renascimento",
        "Renaissance (High)": "Alto Renascimento",
        "Renaissance (generic)": "Renascimento",
        "Rococo": "Rococó",
        "Romanticism": "Romantismo",
        "Surrealism": "Surrealismo",
        "Symbolism": "Simbolismo",
    },
    "es": {
        "Abstract": "Arte abstracto",
        "Abstract Expressionism": "Expresionismo abstracto",
        "Art Deco": "Art déco",
        "Art Nouveau": "Modernismo",
        "Baroque": "Barroco",
        "Bauhaus": "Bauhaus",
        "Conceptual Art": "Arte conceptual",
        "Constructivism": "Constructivismo",
        "Cubism": "Cubismo",
        "Dada": "Dadaísmo",
        "Expressionism": "Expresionismo",
        "Fauvism": "Fauvismo",
        "Folk Art": "Arte popular",
        "Futurism": "Futurismo",
        "Gothic": "Gótico",
        "Impressionism": "Impresionismo",
        "Mannerism": "Manierismo",
        "Minimalism": "Minimalismo",
        "Modernism": "Modernismo",
        "Naturalism": "Naturalismo",
        "Neoclassicism": "Neoclasicismo",
        "Op Art": "Op art",
        "Photorealism": "Fotorrealismo",
        "Pointillism": "Puntillismo",
        "Pop Art": "Arte pop",
        "Post-Impressionism": "Postimpresionismo",
        "Pre-Raphaelite": "Prerrafaelismo",
        "Realism": "Realismo",
        "Renaissance (Early)": "Primer Renacimiento",
        "Renaissance (High)": "Alto Renacimiento",
        "Renaissance (generic)": "Renacimiento",
        "Rococo": "Rococó",
        "Romanticism": "Romanticismo",
        "Surrealism": "Surrealismo",
        "Symbolism": "Simbolismo",
    },
    "nl": {
        "Abstract": "Abstracte kunst",
        "Abstract Expressionism": "Abstract expressionisme",
        "Art Deco": "Art deco",
        "Art Nouveau": "Jugendstil",
        "Baroque": "Barok",
        "Bauhaus": "Bauhaus",
        "Conceptual Art": "Conceptuele kunst",
        "Constructivism": "Constructivisme",
        "Cubism": "Kubisme",
        "Dada": "Dadaïsme",
        "De Stijl": "De Stijl",
        "Expressionism": "Expressionisme",
        "Fauvism": "Fauvisme",
        "Folk Art": "Volkskunst",
        "Futurism": "Futurisme",
        "Gothic": "Gotiek",
        "Impressionism": "Impressionisme",
        "Mannerism": "Maniërisme",
        "Minimalism": "Minimalisme",
        "Modernism": "Modernisme",
        "Naturalism": "Naturalisme",
        "Neoclassicism": "Neoklassicisme",
        "Op Art": "Op-art",
        "Photorealism": "Fotorealisme",
        "Pointillism": "Pointillisme",
        "Pop Art": "Pop-art",
        "Post-Impressionism": "Post-impressionisme",
        "Pre-Raphaelite": "Prerafaëlisme",
        "Realism": "Realisme",
        "Renaissance (Early)": "Vroege Renaissance",
        "Renaissance (High)": "Hoge Renaissance",
        "Renaissance (generic)": "Renaissance",
        "Rococo": "Rococo",
        "Romanticism": "Romantiek",
        "Surrealism": "Surrealisme",
        "Symbolism": "Symbolisme",
    },
}

MEDIA_PARTIAL = {
    "ja": {
        "Acrylic Painting": "アクリル画",
        "Algorithmic Art": "アルゴリズムアート",
        "Ceramics": "陶芸",
        "Charcoal": "木炭画",
        "Clay Sculpture": "粘土彫刻",
        "Collage": "コラージュ",
        "Crayons": "クレヨン",
        "Digital Painting": "デジタル絵画",
        "Enamel": "エナメル",
        "Etching": "エッチング",
        "Fabric": "布",
        "Fractal": "フラクタルアート",
        "Fresco Painting": "フレスコ画",
        "Glass": "ガラス工芸",
        "Glitch": "グリッチアート",
        "Graphite": "グラファイト画",
        "Ink": "墨絵",
        "Metal": "金属彫刻",
        "Neon": "ネオンアート",
        "Oil Painting": "油絵",
        "Origami": "折り紙",
        "Pastel": "パステル画",
        "Pencil": "鉛筆画",
        "Photography": "写真",
        "Printmaking": "版画",
        "Sand": "砂絵",
        "Silk Painting": "絹絵",
        "Stone Carving": "石彫刻",
        "Tapestry": "タペストリー",
        "Textile Art": "テキスタイルアート",
        "Watercolor": "水彩画",
        "Weaving": "織物",
        "Wire Sculpture": "針金彫刻",
        "Wood Sculpture": "木彫",
        "Woodblock Printing": "木版画",
        "Yarn": "毛糸アート",
    },
    "zh": {
        "Acrylic Painting": "丙烯画",
        "Ceramics": "陶瓷",
        "Charcoal": "木炭画",
        "Clay Sculpture": "泥塑",
        "Collage": "拼贴画",
        "Crayons": "蜡笔画",
        "Digital Painting": "数字绘画",
        "Etching": "蚀刻",
        "Fabric": "织物",
        "Fractal": "分形艺术",
        "Fresco Painting": "壁画",
        "Glass": "玻璃艺术",
        "Glitch": "故障艺术",
        "Graphite": "石墨画",
        "Ink": "水墨画",
        "Metal": "金属雕塑",
        "Neon": "霓虹灯艺术",
        "Oil Painting": "油画",
        "Origami": "折纸",
        "Pastel": "粉彩画",
        "Pencil": "铅笔画",
        "Photography": "摄影",
        "Printmaking": "版画",
        "Sand": "沙画",
        "Silk Painting": "绢画",
        "Stone Carving": "石雕",
        "Tapestry": "挂毯",
        "Textile Art": "纺织艺术",
        "Watercolor": "水彩画",
        "Weaving": "编织",
        "Wire Sculpture": "铁丝雕塑",
        "Wood Sculpture": "木雕",
        "Woodblock Printing": "木版画",
        "Yarn": "毛线艺术",
    },
    "ru": {
        "Acrylic Painting": "Акриловая живопись",
        "Ceramics": "Керамика",
        "Charcoal": "Уголь",
        "Clay Sculpture": "Скульптура из глины",
        "Collage": "Коллаж",
        "Crayons": "Восковые мелки",
        "Digital Painting": "Цифровая живопись",
        "Etching": "Офорт",
        "Fractal": "Фрактальное искусство",
        "Fresco Painting": "Фреска",
        "Glass": "Стекло",
        "Glitch": "Глитч-арт",
        "Graphite": "Графит",
        "Ink": "Тушь",
        "Metal": "Металлическая скульптура",
        "Neon": "Неоновое искусство",
        "Oil Painting": "Масляная живопись",
        "Pastel": "Пастель",
        "Pencil": "Карандаш",
        "Photography": "Фотография",
        "Printmaking": "Гравюра",
        "Sand": "Песочное искусство",
        "Silk Painting": "Шёлковая живопись",
        "Stone Carving": "Резьба по камню",
        "Tapestry": "Гобелен",
        "Textile Art": "Текстильное искусство",
        "Watercolor": "Акварель",
        "Weaving": "Ткачество",
        "Wire Sculpture": "Проволочная скульптура",
        "Wood Sculpture": "Деревянная скульптура",
        "Woodblock Printing": "Ксилография",
    },
    "fr": {
        "Acrylic Painting": "Peinture acrylique",
        "Ceramics": "Céramique",
        "Charcoal": "Fusain",
        "Clay Sculpture": "Sculpture en argile",
        "Collage": "Collage",
        "Crayons": "Crayons de couleur",
        "Digital Painting": "Peinture numérique",
        "Etching": "Gravure à l'eau-forte",
        "Fresco Painting": "Fresque",
        "Glass": "Verre",
        "Graphite": "Graphite",
        "Ink": "Encre",
        "Metal": "Sculpture en métal",
        "Oil Painting": "Peinture à l'huile",
        "Pastel": "Pastel",
        "Pencil": "Crayon",
        "Photography": "Photographie",
        "Printmaking": "Estampe",
        "Stone Carving": "Sculpture sur pierre",
        "Tapestry": "Tapisserie",
        "Textile Art": "Art textile",
        "Watercolor": "Aquarelle",
        "Weaving": "Tissage",
        "Wood Sculpture": "Sculpture sur bois",
        "Woodblock Printing": "Gravure sur bois",
    },
    "de": {
        "Acrylic Painting": "Acrylmalerei",
        "Ceramics": "Keramik",
        "Charcoal": "Kohlezeichnung",
        "Clay Sculpture": "Tonskulptur",
        "Collage": "Collage",
        "Crayons": "Buntstifte",
        "Digital Painting": "Digitale Malerei",
        "Etching": "Radierung",
        "Fresco Painting": "Fresko",
        "Glass": "Glas",
        "Graphite": "Graphit",
        "Ink": "Tusche",
        "Metal": "Metallskulptur",
        "Oil Painting": "Ölgemälde",
        "Pastel": "Pastell",
        "Pencil": "Bleistift",
        "Photography": "Fotografie",
        "Printmaking": "Druckgrafik",
        "Stone Carving": "Steinbildhauerei",
        "Tapestry": "Wandteppich",
        "Textile Art": "Textilkunst",
        "Watercolor": "Aquarell",
        "Weaving": "Weberei",
        "Wood Sculpture": "Holzskulptur",
        "Woodblock Printing": "Holzschnitt",
    },
    "it": {
        "Acrylic Painting": "Pittura acrilica",
        "Ceramics": "Ceramica",
        "Charcoal": "Carboncino",
        "Clay Sculpture": "Scultura in argilla",
        "Collage": "Collage",
        "Crayons": "Pastelli a cera",
        "Digital Painting": "Pittura digitale",
        "Etching": "Acquaforte",
        "Fresco Painting": "Affresco",
        "Glass": "Vetro",
        "Graphite": "Grafite",
        "Ink": "Inchiostro",
        "Metal": "Scultura in metallo",
        "Oil Painting": "Pittura a olio",
        "Pastel": "Pastello",
        "Pencil": "Matita",
        "Photography": "Fotografia",
        "Printmaking": "Stampa artistica",
        "Stone Carving": "Scultura in pietra",
        "Tapestry": "Arazzo",
        "Textile Art": "Arte tessile",
        "Watercolor": "Acquerello",
        "Weaving": "Tessitura",
        "Wood Sculpture": "Scultura in legno",
        "Woodblock Printing": "Xilografia",
    },
    "pt": {
        "Acrylic Painting": "Pintura acrílica",
        "Ceramics": "Cerâmica",
        "Charcoal": "Carvão",
        "Clay Sculpture": "Escultura em argila",
        "Collage": "Colagem",
        "Crayons": "Lápis de cor",
        "Digital Painting": "Pintura digital",
        "Etching": "Gravura em metal",
        "Fresco Painting": "Afresco",
        "Glass": "Vidro",
        "Graphite": "Grafite",
        "Ink": "Tinta nanquim",
        "Metal": "Escultura em metal",
        "Oil Painting": "Pintura a óleo",
        "Pastel": "Pastel",
        "Pencil": "Lápis",
        "Photography": "Fotografia",
        "Printmaking": "Gravura",
        "Stone Carving": "Escultura em pedra",
        "Tapestry": "Tapeçaria",
        "Textile Art": "Arte têxtil",
        "Watercolor": "Aquarela",
        "Weaving": "Tecelagem",
        "Wood Sculpture": "Escultura em madeira",
        "Woodblock Printing": "Xilogravura",
    },
    "es": {
        "Acrylic Painting": "Pintura acrílica",
        "Ceramics": "Cerámica",
        "Charcoal": "Carboncillo",
        "Clay Sculpture": "Escultura en arcilla",
        "Collage": "Collage",
        "Crayons": "Crayones",
        "Digital Painting": "Pintura digital",
        "Etching": "Aguafuerte",
        "Fresco Painting": "Fresco",
        "Glass": "Vidrio",
        "Graphite": "Grafito",
        "Ink": "Tinta",
        "Metal": "Escultura en metal",
        "Oil Painting": "Pintura al óleo",
        "Pastel": "Pastel",
        "Pencil": "Lápiz",
        "Photography": "Fotografía",
        "Printmaking": "Grabado",
        "Stone Carving": "Talla en piedra",
        "Tapestry": "Tapiz",
        "Textile Art": "Arte textil",
        "Watercolor": "Acuarela",
        "Weaving": "Tejido",
        "Wood Sculpture": "Escultura en madera",
        "Woodblock Printing": "Xilografía",
    },
    "nl": {
        "Acrylic Painting": "Acrylschilderij",
        "Ceramics": "Keramiek",
        "Charcoal": "Houtskool",
        "Clay Sculpture": "Kleisculptuur",
        "Collage": "Collage",
        "Crayons": "Kleurpotloden",
        "Digital Painting": "Digitale schilderkunst",
        "Etching": "Ets",
        "Fresco Painting": "Fresco",
        "Glass": "Glas",
        "Graphite": "Grafiet",
        "Ink": "Inkt",
        "Metal": "Metalen sculptuur",
        "Oil Painting": "Olieverfschilderij",
        "Pastel": "Pastel",
        "Pencil": "Potlood",
        "Photography": "Fotografie",
        "Printmaking": "Grafiek",
        "Stone Carving": "Steensnijden",
        "Tapestry": "Tapijt",
        "Textile Art": "Textielkunst",
        "Watercolor": "Aquarel",
        "Weaving": "Weven",
        "Wood Sculpture": "Houtsculptuur",
        "Woodblock Printing": "Houtsnede",
    },
}

ALL_LOCALES = ["en", "zh", "nl", "fr", "de", "it", "ja", "pt", "ru", "es"]

for locale in ALL_LOCALES:
    path = os.path.join(BASE, f"{locale}.json")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    # Build complete namespace: every key present, translated if available, else English
    movement_overrides = MOVEMENTS_PARTIAL.get(locale, {})
    media_overrides = MEDIA_PARTIAL.get(locale, {})

    data["stylebearMovements"] = {name: movement_overrides.get(name, name) for name in MOVEMENTS_EN}
    data["stylebearMedia"] = {name: media_overrides.get(name, name) for name in MEDIA_EN}

    translated_m = sum(1 for k in MOVEMENTS_EN if movement_overrides.get(k, k) != k)
    translated_mt = sum(1 for k in MEDIA_EN if media_overrides.get(k, k) != k)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{locale}.json: {translated_m}/{len(MOVEMENTS_EN)} movements translated, "
          f"{translated_mt}/{len(MEDIA_EN)} media translated")
